services:
  innovatube:
    container_name: innovatube
    # construir imagen 
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    # o desde el docker hub
    image: fhers13/innovatube:v1
    ports:
    - "80:80"
    expose:
      - 80
    tty: true
    restart: unless-stopped