# version: '3.1'
services:    
  database:
      container_name: database
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: innovadb
      ports:
        - 3306:3306